### ISSUE TITLE
FB login bug

### ISSUE THREAD

**Issue by wnasich** [webtechnick/CakePHP-Facebook-Plugin#10]
Currently there is a issue on FB Connect related to this bug http://bugs.developers.facebook.net/show_bug.cgi?id=14971

**Comment by ilijamitkov** [comment]
I have problem with the facebook plugin after i include the 
var $components = array('Session','Facebook.Connect'); in the app controller the site just keeps refreshing in chrome and in Mozila its ok

**Comment by wnasich** [comment]
maybe is a redirect issue. Try to see the http headers.

**Comment by daVinciWanaB** [comment]
I'm having the same issue in Chrome - if I login to Facebook (at facebook.com), then load my site (not localhost), it just refreshes in a non-stop loop.

**Comment by webtechnick** [comment]
The redirect issue is usually a symtom of misconfiguration of the cookie setting in config/facebook.php
