### ISSUE TITLE
Plugin seems not working with latest cakephp version

### ISSUE THREAD

**Issue by DamianoBuscemi** [webtechnick/CakePHP-Facebook-Plugin#103]
Can you help?
The helper does not show the logout,
moreover if you force logout with auth, $this->Auth->logout();
the plugin recreates the session and you are permanently logged in.

Do you have any hint in order to use the plugin?

**Comment by justKingo** [comment]
Same problem here with CakePHP 2.2.x! The Logout Button shows if I use

```
$this->Auth->logout();
```

In that way the auth logout would not work. If I echo

```
$this->Facebook->logout(array('redirect' => array('controller' => 'users', 'action' => 'logout')));
```

the logout button does not show :(

Another problem occurs if I want to access the user information of facebook login. In the video tutorial it's possible to access with the following code:

```
//AppController
public function beforeFilter() {
   $this->set('facebook_user', $this->Connect->user());
}
```

and

```
//View
debug($facebook_user);
```

Is there a new solution now?

**Comment by dft87** [comment]
I have same problem, can someone fix this?
$this->Connect->user()
always return 0

**Comment by rekik-mehdi** [comment]
I get the same problem, it is solved when i updated vendors files with new facebook-php-sdk "3.2.1"

**Comment by webtechnick** [comment]
Updated plugin vendor files to latest facebook SDK 3.2.1 in master branch.
