### ISSUE TITLE
FB::api('/me') always return null

### ISSUE THREAD

**Issue by kwunyeung** [webtechnick/CakePHP-Facebook-Plugin#109]
I'm using the latest master. It always return null when I call FB::api('/me') but it works when I call FB::api('/my_fb_id'). I have added "user_like" permission in my app but FB::api('/user_id/likes/page_id') only gives

array(
    'data' => array()
)

Is there any problem here?

**Comment by dsgrant07** [comment]
Hey kwunyeung!!

Did you ever find the reason or cause of this. I'm seeing the same problem almost 2 years later. Should this plugin be abandoned? Or am I doing something wrong?

Regards,

**Comment by kwunyeung** [comment]
@dsgrant07 I'm not sure if it's still useful for you. I had 2 times with this issue. They are just some minor mistakes I made.
1. I added an extra space after the app secret in facebook.php after copy and paste from developer.facebook.com
2. After adding the permission request with the login url it was fine. e.g. 'scope' => 'email'

Hope this help.

Cheers,
Kwun.
