### ISSUE TITLE
Update FB SDK to 3.0

### ISSUE THREAD

**Issue by randallb** [webtechnick/CakePHP-Facebook-Plugin#13]
https://github.com/facebook/php-sdk

The new version includes OAuth2.0 support, which is required before September 1st.

**Comment by webtechnick** [comment]
I've created a branch to update to 3.0, however the latest fbxml implimentation along with javascript sdk is not cross compatible with the new 3.0 PHP SDK.  As such, all the fbxml magic (login/logout) is not functional using the new PHP SDK 3.0. I've created a ticket.

https://github.com/facebook/php-sdk/issues/392

This is a rather big issue as a large portion of this plugin relies on the fact fbxml and the PHP SDK can talk to one another without an issue.  If I updated to 3.0 today, I'd have to refactor the entire helper to use FB->getLoginUrl instead and it wouldn't look nearly as nice as it wouldn't be a popup interface, rather just a navigation away then redirect back.

I will keep a close eye on it, once they fix the issue I'll roll back the changes to 3.0 and we'll be rocking.   For now we're standing still on the previous implementation.

**Comment by randallb** [comment]
Yup. Sounds solid. Thanks for taking a look so quickly.

**Comment by randallb** [comment]
Whoops, didn't mean to close. Sorry.

**Comment by rinatkhaziev** [comment]
tried version 2.6.0. for some reason $this->Connect->hasAccount (when called from controller, return void).
If i do it like,
echo $this->hasAccount 
in component's method it works. Not sure why is that, so i ended up using v2.6.0 for all offline access routines, and previous version for front-end

**Comment by kenvunz** [comment]
https://developers.facebook.com/blog/post/534/

Looks like they have fixed the problem, any eta on reverting plugin to use OAuth?

Cheers
Ken

**Comment by webtechnick** [comment]
This is now done and in the master branch.
