### ISSUE TITLE
Double entry in database including one empty

### ISSUE THREAD

**Issue by florianajir** [webtechnick/CakePHP-Facebook-Plugin#133]
Hi,
After the facebook login, there is a double call of methods facebook related to login (before & after)  in the AppController and the plugin create me two entries in my database, one correct and one empty for each user..

the problem seems to become from the plugin on synchronisation .

**Comment by DColl** [comment]
can you edit and tidy up your comment please ? Use https://help.github.com/articles/github-flavored-markdown#syntax-highlighting and remove the unnecessary comments in the code.
Simply put 3 times ` followed by php
