### ISSUE TITLE
Facebook mobile connect does not work.

### ISSUE THREAD

**Issue by matibaski** [webtechnick/CakePHP-Facebook-Plugin#150]
Hi everyone...

I am having trouble with the Facebook connect via mobile phones / smartphones.
To register the user via Facebook I am using the login()-function. After the user's logged in, I write his data into a database for future logins.

This code I am using to log in:
<?php
echo $this->Facebook->login(array(
    'perms'=>'email, publish_stream', 
    'redirect' => 'register_fb', 
    'label' => '<i class="icon-white icon-chevron-right"></i>' . __d('translate', 'Mit Facebook registrieren'), 
    'class'=>'btn btn-info')); 
?>
See image: screenshot_1.png

On the desktop the login works very well!

On mobile it redirects the user (in the popup/new window) to this url:
https://m.facebook.com/dialog/oauth?app_id=436490563122999&client_id=436490563122999&display=touch&domain=***MY-DOMAIN***&e2e=%7B%7D&locale=de_DE&origin=2&redirect_uri=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D28%23cb%3Df3b0da75cc%26domain%3D***MY-DOMAIN***%26origin%3Dhttp%253A%252F%252F***MY-DOMAIN*%252Ff3fcc9c438%26relation%3Dopener%26frame%3Df33a10f7a4&response_type=token%2Csigned_request&scope=email&sdk=joey

It's only a blank/white page and nothing happens. See image: screenshot_2.png

I am using the newest version (3.1.2) on an Apache2 webserver with MySQL 5 and PHP 5.3.
The dumb thing in this error is, that I can't debug anything in a console on a smartphone...

I am very thankful to any help...
Kind regards,
matibaski

![screenshot_1](https://f.cloud.github.com/assets/2587920/1561476/2c0b7e1a-5032-11e3-86fa-92973d78f26e.png)
![screenshot_2](https://f.cloud.github.com/assets/2587920/1561477/2c101b96-5032-11e3-8a87-c08c76ad1350.png)

**Comment by matibaski** [comment]
I could check the connect on Android and Windows OS, and there it works well.
I also checked for older iOS versions like 6.\* and 5.\* and there it works too.

So it's an iphone iOS 7 problem only.

**Comment by amjo** [comment]
It works perfectly here on IOS 7... Make sure popup is user initiated, and also make sure your FB Api is the latest along with the certificate 

-----Original Message-----

**Comment by matibaski** [comment]
Hmm well, I am using the cakePHP function $this->Facebook->login(), which adds
onclick="login('/users/register_fb');"
to the HTML code.

I figured out, that when I create the Login Button without the onclick attribute, but with the href="javascript:login();" attribute, it works.

Thanks for your hint @amjo 

Kind regards...
