### ISSUE TITLE
FB Api Not Working, Update the Facebook SDK on Vendors Folder with Newest SDK

### ISSUE THREAD

**Issue by eddOrnelas** [webtechnick/CakePHP-Facebook-Plugin#151]
Like the title says, i was using this plugin cause it let met init the facebook api wherever i want, but in testing i could not run the simplest function like getUser() or api('/me'); so i updated my facebook sdk/lib from vendors folder and now works like charm.

Regards.

**Comment by webtechnick** [comment]
Pulled in newest PHP SDK into master.
