### ISSUE TITLE
unidefined property:Facebook 

### ISSUE THREAD

**Issue by Creator2010** [webtechnick/CakePHP-Facebook-Plugin#16]
I have trying the fix this error.i seem not to know its source. Notice (8): Undefined property: View::$Facebook [APP\views\pages\display.ctp, line 3].

please help

**Comment by webtechnick** [comment]
Make sure you have the helper defined in the controller you want to use, or app_controller.php if you want it available in every view.

var $helpers = array('Facebook.Facebook');

**Comment by Creator2010** [comment]
i placed this code in the app_controller :-var $helpers = array('Session','Facebook.Facebook');

**Comment by Creator2010** [comment]
thanks.I have fixed the problem.i placed the var $helpers = array('Facebook.Facebook'); in the app_controller.php in the controller folder.I initially placed it in the app_controller.php in the app folder
