### ISSUE TITLE
OAuth2 Incompatibility Issue

### ISSUE THREAD

**Issue by robksawyer** [webtechnick/CakePHP-Facebook-Plugin#19]
I keep getting the following error. Any ideas?

Error: FB.Auth.setSession incompatible with OAuth2.

Facebook config:
<?php
$config = array(
    'Facebook' => array(
        'appId'  => '244224708951284',
        'apiKey' => '9747b40bc8bf0d6fd5ce3c7f71848136',
        'secret' => 'fcf31bb815c9a6ee21101ff2e2dadfb1',
        'cookie' => true,
        'locale' => 'en_US'
        //'xfbml' => true,
        //'oauth' => true
    )
);
?>

Facebook app settings:
Remove Deprecated Auth Methods   - Enabled
Stream post URL security  - Disabled
signed_request for Canvas - Enabled
Timezone-less events - Enabled
Upgrade to Requests 2.0 -  Disabled
iframe Page Tab - Enabled
Require manage_notifications - Enabled
OAuth Migration - Disabled
Develop Using Deprecated FBML Canvas - Disabled

**Comment by webtechnick** [comment]
This has been resolved in latest version v3.1.1.  Please update your application accordingly.
