### ISSUE TITLE
Nothing displayed

### ISSUE THREAD

**Issue by Thoes** [webtechnick/CakePHP-Facebook-Plugin#2]
Hi Nick,

After following the instructions from the Readme file I wanted to display a comment box. However; nothing is displayed, no comment box and no errors.

I have uploaded all files to the facebook directory within plugins, changed the settings in the config file, loaded the helper (the <html> tag is correctly changed, as well as the javascript that's added to the bottom of my page), but nothing happens.

Any ideas? Thanks in advance!

**Comment by webtechnick** [comment]
Did you setup your Facebook application correctly? Do you have your configuration file setup within app/config/facebook.php?  If so, I'd have to take a look at your view/layout page to determine what's going on.

**Comment by webtechnick** [comment]
Please refer to the example app for inspiration: http://svn.xp-dev.com/svn/facebook_example_app/

**Comment by kevenages** [comment]
I've run into the same problem.  My FB app is correct, config on the plugin correct.
I have verified that for the fanbox to work, I have to hardcode the appId into the function.  Config:read won't read from facebook.php

**Comment by webtechnick** [comment]
Please verify it is in the correct directory. It needs to be in your APP/config not in the plugin/facebook/config.php

Thanks,
Nick

**Comment by kevenages** [comment]
It is 100% in the correct directory.
If add configure:read I still get nothing.  I modified helpers/facebook.php to read as follows:

function fanbox($options = array()){
    debug('test' . Configure::read('Facebook.appId'));
    $options = array_merge(
      array(
        'profile_id' => Configure::read('Facebook.appId'),
        'stream' => 0, 
        'logobar' => 0, 
        'connections' => 0,
      ),
      $options
    );
    return $this->__fbTag('fb:fan', '', $options);
  }

---

The only thing that prints is test

**Comment by kevenages** [comment]
I should also mention that I don't have the plugin installed in app/plugins, but rather the parent plugin directory

**Comment by webtechnick** [comment]
You must have not run the init in your layout.  Make sure you run the $this->Facebook->init(); in your application layout as it will load and read the configuration file for the rest of the helper.

**Comment by kevenages** [comment]
Yea I did that too.  I just ended up hardcoding it into the fanbox (not ideal I know).
Thanks much for your quick reply (as always :D)
