### ISSUE TITLE
Share and comments can't be used together

### ISSUE THREAD

**Issue by iluuuk** [webtechnick/CakePHP-Facebook-Plugin#22]
Hi,

I'm writing a facebook application using this wonderful plugin, thanks!
I'm wondering though, why both comments and share function work when used separately, but stop working when used together?
If i try to use them both i only get the share button (no comments). why is that? minor bug or am i confused in smth?

thanks!

Lucas

**Comment by kikein** [comment]
Hi!,

Same issue here.

Do u know the reason?

Thanks!

**Comment by iluuuk** [comment]
hi,

sorry, no idea, and still no answer... i'm just focusing on other stuff. I think this plugin is not properly working with PHP SDK 3.1.1, cuz i got some other weird issues when running my app through facebook. (see https://github.com/webtechnick/CakePHP-Facebook-Plugin/issues/23)

good luck with that! if you find something out let me know! i'll do the same

**Comment by webtechnick** [comment]
The share by default uses the JS without FBXML, if you are using more of the advanced featuers of the plugin (comments) you will need to pass in the fbxml flag into the share options.

```
$this->Facebook->share(Router::url($this->here, true), array(
  'fbxml' => true
));
```
