### ISSUE TITLE
FB Login button doesn't appear on Firefox

### ISSUE THREAD

**Issue by ghost** [webtechnick/CakePHP-Facebook-Plugin#24]
Just followed the tutorial exactly as you had it in the screencast.

<?php echo $this->Facebook->login(); ?> gets converted to fb:login-button but does not get turned into an actual login button in Firefox 6.0.2 at least.  Doubt its a problem with your code, seems more like something to do with Firefox, but just thought I'd let you know and see if you have any ideas.

**Comment by emrrahgul** [comment]
can you please let us no how you solved it
