### ISSUE TITLE
CakePHP 2.0 and the Facebook Plugin

### ISSUE THREAD

**Issue by joshuaswilcox** [webtechnick/CakePHP-Facebook-Plugin#28]
I can't seem to get this to work with cakephp 2.0.  Is there something in the plugin that needs to change, or is there any timeline for when it might work? I followed your steps to a T and it was working fine in 1.3, but I have a new site that is written with 2.0 that needs this.  Thanks!

**Comment by webtechnick** [comment]
No it doesn't work in 2.0 yet, but it's coming soon.

Nick

**Comment by joshuaswilcox** [comment]
Great, thanks!  I actually saw your blog post about it.  Thanks for your great work on this plugin!

**Comment by webtechnick** [comment]
Thanks, I just released a beta version for CakePHP 2.0 in it's own branch: https://github.com/webtechnick/CakePHP-Facebook-Plugin/tree/cakephp2.0
