### ISSUE TITLE
Login/Logout buttons

### ISSUE THREAD

**Issue by darkropo** [webtechnick/CakePHP-Facebook-Plugin#31]
Hi, i added the follow code to my home.ctp page but the login/out button don't work properly.

<?php       if($facebook_user): ?>
 <?php           echo $this->Facebook->logout(); ?>
 <?php           echo debug($facebook_user); ?>
 <?php       else: ?>
 <?php           echo $this->Facebook->login(); ?>
 <?php           echo 'Ejemplo Segundo'; ?>
 <?php       endif;    ?>

it seems like the redirect don't work at all, what im doing wrong?

**Comment by webtechnick** [comment]
Please verify you have $this->Facebook->init(); somewhere in your layout/view.
