### ISSUE TITLE
Use of Router::url($this->here) breaks subfolder sites

### ISSUE THREAD

**Issue by ghost** [webtechnick/CakePHP-Facebook-Plugin#32]
If your Cake application runs from within a folder (e.g. http://example.com/cakephp_application/) Router::url($this->here, true) will create a link which duplications the subfolder structure (e.g. http://example.com/cakephp_application/cakephp_application/).
The fix is to use Router::url(null, true) as the Router::url function only handles urls relative to your app webroot, not your domain webroot.

**Comment by webtechnick** [comment]
This has been resolved in latest release.
