### ISSUE TITLE
1.3 Current FB SDK needs to be upgraded.

### ISSUE THREAD

**Issue by ghost** [webtechnick/CakePHP-Facebook-Plugin#33]
The current version (included in your plugin) incorrectly handles FB session cookies which are used for login. The latest version of the FB PHP SDK appears to work fine.

**Comment by webtechnick** [comment]
There is a branch that handles the new OAuth2.0 but it wasn't stable enough for master as it broke tests and not all documented fuctionality wasn't working.  As such the stable branch (master) is kept back until it's done.  Right now I'm concentrating on a stable 2.0 branch and once that's done I'll refocus my energy on the last stable 1.3 branch.  All future development will be made on 2.0 after that.
