### ISSUE TITLE
Class 'Facebook' not found

### ISSUE THREAD

**Issue by enesk** [webtechnick/CakePHP-Facebook-Plugin#35]
Hi,

i'm trying to use the plugin but i can't bring it on work. I get following:

Fatal error: Class 'Facebook' not found in /Users/eneskul/Desktop/vhosts/game/htdocs/app/Plugin/Facebook/libs/f_b.php on line 22

My AppController:

```
public $components = array('Session',
    'Auth' => array(
        'authenticate' => array(
            'Form' => array(
                'fields' => array('username' => 'email')
            )
        ),
        'authorize' => 'Controller'
    ),
    'Facebook.Connect' => array('model' => 'User')
);


function beforeFilter()
{
    //Configure AuthComponent

    $this->Auth->allow('*');
    $this->Auth->loginAction = array('controller' => 'users', 'action' => 'login');
    $this->Auth->logoutRedirect = array('controller' => 'users', 'action' => 'login');
    $this->Auth->loginRedirect = array('controller' => 'users', 'action' => 'index');
}
```

CakePHP version 2.0.3

**Comment by ShashankaNataraj** [comment]
Before closing the issue please mention whether it was closed because you solved it, or the error doesnt exist anymore.

Now Im stuck with the exact same issue, and have no way of knowing the soluiton.

**Comment by damln** [comment]
What is the solution please ? I have the same error. Thank you.
