### ISSUE TITLE
Custom Login Permissions

### ISSUE THREAD

**Issue by leckstein** [webtechnick/CakePHP-Facebook-Plugin#38]
Firstly this is a great plugin that saved me loads of time, thank you!

The login control is ignoring permissions when custom is set to true because the 'scope' option is hard coded to 'email' in the javascript login function.

I fixed this by passing through the perms string to the login function, for reference here are my changes to the FacebookHelper class:
113 -  $perms = isset($options['perms']) ? $options['perms'] : 'email';
       $onclick = "login('".$options['redirect']."', '".$perms."');";

497 - function login(redirection, perms){

510 - }, {scope: perms});

**Comment by webtechnick** [comment]
Thank you for reporting this issue. This is no longer the case in master. Please refer to the lastest release 3.1.1.
