### ISSUE TITLE
Make extending "User" object easier

### ISSUE THREAD

**Issue by meliho** [webtechnick/CakePHP-Facebook-Plugin#4]
It would be nice if it were easier to extend the "User" object so that more than the Facebook ID can be saved as part of the Auth registration flow

**Comment by webtechnick** [comment]
You can,  the entire login process is completely shortcutable so you can save whatever data you'd like.

Set createUser to false on your setup and then do whatever you want in beforeFilter

$var components = array('Auth', 'Facebook.Connect' => array('createUser' => false));

function beforeFilter(){
  if($this->Connect->me){
     //You have a logged in facebook user, do whatever you want with them.
     if($this->Connect->hasAccount){
        //they already have an account, log them in as normal
     }
     else {
        //they don't have an account, save whatever you want.
     }
  }
}

Hope that helps,
Nick

**Comment by meliho** [comment]
Sorry, I never came back to say thank you. This helped a ton!

**Comment by webtechnick** [comment]
This has been resolved in cakephp2.0 branch with this commit https://github.com/webtechnick/CakePHP-Facebook-Plugin/commit/2e83573883d767cc6814a726b29840351b2f3dbb
