### ISSUE TITLE
FB oAuth 2.0 update breaks plugin

### ISSUE THREAD

**Issue by loganbest** [webtechnick/CakePHP-Facebook-Plugin#40]
With today's Facebook update all apps that are using this plugins Facebook Login is broken, including the demo on facebook.webtechnick.com. 

This needs to be fixed as it cripples many sites.

**Comment by sbacelic** [comment]
Looks like a problem with cross domain communication:

Unsafe JavaScript attempt to access frame with URL https://s-static.ak.fbcdn.net/connect/xd_proxy.php?version=3#cb=f15e82491c&origin=http%3A%2F%2Flocalhost.localdomain%3A8080%... from frame with URL http://localhost.localdomain:8080/. Domains, protocols and ports must match.

This will be a long night 4 me ;) when and If found a solution I'll share here

**Comment by loganbest** [comment]
Same here haha.

**Comment by loganbest** [comment]
On /views/helpers/facebook.php:416 you should see:

```
xfbml : true // parse XFBML
```

If you change that to this: 

```
xfbml : true, // parse XFBML
oauth: false
```

Then the fblogin will be able to work, although I'm afraid as to how long that will be able to work since Facebook is now Mandating that everyone use OAUTH to login and logout.

via: https://developers.facebook.com/blog/post/525/

**Comment by sbacelic** [comment]
Tnx, I needed quick fix as site was unusable atm :)

**Comment by loganbest** [comment]
Hopefully we get a permanent fix soon...

**Comment by webtechnick** [comment]
I'm working on a permanent resolution.

**Comment by webtechnick** [comment]
Updated to 3.1.1 in master -- merged php_sdk_3 after update to newest PHPSDK.  Working in dev and production demo: http://facebook.webtechnick.com

Please update your applications accordingly.  Enjoy!  

CakePHP 2.0 development is still going strong, hope to have a RC soon.

**Comment by mattjwhelan** [comment]
We're using this plugin on a handful of sites in Asia. We're not terribly familiar w/ the Facebook APIs/SDKs on a technical level. Will very much appreciate the permanent fix when it comes. Thanks for maintaining this code. :)

**Comment by sbacelic** [comment]
Permanent fix is already deployed, problem was with old FB SDK. Just update your code from master branch
