### ISSUE TITLE
Fatal error: Facebook not found in /Plugin/Facebook/libs/f_b.php

### ISSUE THREAD

**Issue by alexgenovese** [webtechnick/CakePHP-Facebook-Plugin#45]
Hello, 
I have installed in /app/plugin/ the Facebook Plugin in Cakephp 2.0.5 but it doesn't work fine.

Steps: 
1. copied the plugin in in app/plugin/
2. facebook.php copied in app/config/ configuration files with all configuration codes.
3. replaced the layout with that in the example

the error is:

<pre>
Fatal error: Class 'Facebook' not found in /Applications/MAMP/htdocs/emailmarketing/app/Plugin/Facebook/libs/f_b.php on line 21
</pre>

Thanks in advance
Alex Genovese

**Comment by failure84** [comment]
Any solution for this ?

**Comment by failure84** [comment]
clone git: git clone git://github.com/webtechnick/CakePHP-Facebook-Plugin facebook && cd facebook
Change branch to cakephp-2.0: git checkout remotes/origin/cakephp2.0

It is good to run the right branch, close this ticket please!
