### ISSUE TITLE
Call to undefined method SessionComponent::start() connect.php on line 64

### ISSUE THREAD

**Issue by emrrahgul** [webtechnick/CakePHP-Facebook-Plugin#59]
i created app which has user authentication all ready, i want to implement facebook plugin but after entering 

var $components = array('Auth', 'Session','Facebook.Connect');
var $helpers = array('Html', 'Form', 'Js', 'Session', 'Facebook.Facebook');       

i get an error

Fatal error: Call to undefined method SessionComponent::start() in /Users/emrahgul/Sites/evento2/app/Plugin/Facebook/controllers/components/connect.php on line 64

can some one help

**Comment by sangregoriopaolo** [comment]
Probably you are using CakePHP 2 with the plugin taken from the master? SessionComponent::start() is not longer available in CakePHP 2

**Comment by webtechnick** [comment]
You're using the 1.3 version of the plugin in CakePHP 2.0.  Please use the cakephp2.0 branch in your CakePHP 2.x projects.
