### ISSUE TITLE
Class 'Facebook' not found

### ISSUE THREAD

**Issue by emrrahgul** [webtechnick/CakePHP-Facebook-Plugin#62]
Hi,

i'm trying to use the plugin but i can't bring it on work. I get following:

Fatal error: Class 'Facebook' not found in /Users/emrahgul/Sites/evento/app/Plugin/Facebook/libs/f_b.php on line 21

public function __construct() {
    if (empty(self::$Facebook)) {
            self::$Facebook = new Facebook(FacebookInfo::getConfig());
        }
  }

CAKEPHP FACEBOOK PLUGIN version  3.1.1

**Comment by webtechnick** [comment]
You're trying to use the 1.3 version in CakePHP 2.0.  Please use the cakephp2.0 branch of the plugin.  Thanks.
