### ISSUE TITLE
 function html() on a non-object

### ISSUE THREAD

**Issue by emrrahgul** [webtechnick/CakePHP-Facebook-Plugin#64]
i download the file in https://github.com/webtechnick/CakePHP-Facebook-Plugin/tree/cakephp2.0
and followed the instructions but i seem to get an error when i add "Facebook.Connect" in AppController.php
here is the AppController code

class AppController extends Controller {

```
var $uses = array('Messages.Message', 'Settings', 'User');
var $components = array('Auth', 'Session', 'Facebook.Connect' );
var $helpers = array('Html', 'Form', 'Js', 'Session', 'Facebook.Facebook');
```

and the code for default.ctp is

<?php echo $this->Facebook->html(); ?>
<head>
<title></title>
<
</head>
<body>

<div id="container">
<?php echo $this->Facebook->share(); ?>

    <div id="header">

</div>

<div id="main">

</div>

<div id="footer">

</div>
    

</div>
<?php echo $this->element('sql_dump'); ?>
<?php echo $this->Facebook->init(); ?>

</body>
</html>

Fatal error: Call to a member function html() on a non-object in app/View/Layouts/default.ctp on line 2

**Comment by webtechnick** [comment]
Make sure you CakePlugin::load('Facebook'); in your bootstrap.php file.  Also make sure you have the correct branch checked out into your Plugin/Facebook directory.

The quickest way to check is the directory structure of the plugin, it should meet 2.x standards, not 1.x standards.

**Comment by emrrahgul** [comment]
Nick i followed all the instructions you given 
yes i do have  CakePlugin::load('Facebook'); in my bootstrap.php file.

file struct is 
Pluging
    Facebo0k
    Config
        -facebook.php.example
    Controllers
        Component
            -ApiComponent.php
            -ConnectComponent.php

```
Lib
    -FacebookApi.php
    -FacebookInfo.php
    -FB.php

Tests
    Case
        Component
            -ConnectComponentTest.php
    View
        Helper
            -FacebookHelperTest.php

Vendor
    img
        -facebook-logout.png
    -fb_ca_chain_bundle.crt
    -base_facebook.php
    -channel.php
    -Facebook.php

    View
        Helper
            -FacebookHelper.php

webroot
    img
        -connectwithfacebook.gif
        -facebook_logout.jpg
        -facebook-logout.png
receiver
    -xd_receiver.htm

readme.markdown
FacebookAppController.php.php
FacebookAppModel.php
```

**Comment by emrrahgul** [comment]
i actually copied all the files one by one in https://github.com/webtechnick/CakePHP-Facebook-Plugin/tree/cakephp2.0
