### ISSUE TITLE
Fatal error!!!

### ISSUE THREAD

**Issue by AloneWalk** [webtechnick/CakePHP-Facebook-Plugin#65]
my problem is,if i run my apps on web project.facebookviet.vn,no problem
but when i run my apps on host sieu.vn,have one error:

Fatal error: Uncaught GraphMethodException: Unsupported get request. thrown in  mydomain\wwwroot\apps\base_facebook.php on line 1033
and in fbmain.php have one a error:
Fatal error: Class 'Facebook' not found in D:\Domains\sieu.vn\wwwroot\apps\fbmain.php on line 26
i don't know,please help me
thank all!

**Comment by soufianeh** [comment]
I think the errors are pretty clear, did you make sure that you got the path right?

Also, when testing anything Facebook locally, you need to map your "localhost" to a valid domain name (edit  your hosts file)
