### ISSUE TITLE
session_start() [function.session-start]

### ISSUE THREAD

**Issue by emrrahgul** [webtechnick/CakePHP-Facebook-Plugin#66]
following error comes up after following nick's instructions
Warning (2): session_start() [function.session-start]: Cannot send session cookie - headers already sent by (output started at /app/Plugin/Facebook/Vendor/Facebook.php:1) [APP/Plugin/Facebook/Vendor/Facebook.php, line 37]

and also the login button does not show up

there is also a strange thing, when i'm loged into facebook it show all the people who is the administrators for the facebook app

**Comment by kinglove** [comment]
Me too, can anybody help me ?
