### ISSUE TITLE
Class 'FB' not found

### ISSUE THREAD

**Issue by roseroja** [webtechnick/CakePHP-Facebook-Plugin#7]
hi,

i am using 2.1.1 facebook plugin in cakephp but it is not working. 
every time show "Fatal error: Class 'FB' not found in /app/controllers/components/connect.php on line 61 "
this error.

please help

roseroja

**Comment by webtechnick** [comment]
Why is it in your app/ directory?  You'll need to install the plugin into /plugins/facebook/

Hope that helps,
Nick

**Comment by roseroja** [comment]
all three file 

f_b.php
facebook_api.php
facebook_info.php

put on plugins/facebook folder 
but display Fatal error  

Fatal error: Class 'Facebook' not found in \app\plugins\facebook\f_b.php on line 22
please tell me what we do.

please help

**Comment by sorenlouv** [comment]
This is probably due to CakePHP 2.0 - looking forward for an upgrade :)
