### ISSUE TITLE
Fatal error: Class 'FacebookInfo' not found in C:\wamp\www\websites\facebook_example\app\views\helpers\facebook.php on line 38

### ISSUE THREAD

**Issue by ghost** [webtechnick/CakePHP-Facebook-Plugin#73]
App::import('Lib', 'Facebook.FacebookInfo');
class FacebookHelper extends AppHelper {

function __construct($settings = array()){

```
    $this->_set($settings);
    if(!$this->locale){
        $this->locale = FacebookInfo::getConfig('locale');
    }
    if(!$this->locale){
        $this->locale = 'en_US';
    }
    parent::__construct();
}
```

}

This part of code seems to be the problem. I did everything as it is in Nick's video, any suggestions? 

You see the file is imported, so I think the problem might be either in routes.php or my wamp server application functions/extensions.

**Comment by ghost** [comment]
Ok, the problem was I didn't put the plugin in plugin folder. Importing a lib requires it's filename, but Facebook. tells us it is inside plugins/facebook folder.

**Comment by rmenezes** [comment]
krysavcik I have the same problem. Did put your plugin inside "app/plugin" or just "plugin"?

**Comment by ghost** [comment]
You have to put Nick's plugin files in app/plugin/facebook - this way Facebook.FacebookInfo points to plugin named "facebook" to helper named "facebook_info.php". Which is exactly what we need. My mistake was to mix plugin's files with files in my app directory, hence the error.

Always read the description carefully.
