### ISSUE TITLE
Cake1.3 and Facebook-Plugin

### ISSUE THREAD

**Issue by rmenezes** [webtechnick/CakePHP-Facebook-Plugin#74]
I'm using cake version 1.3 and the new version of Nick's plugin but I have some problems. When try to call some facebook function like "<?= $facebook->share(); ?>" in my view page, nothing happening. Could anyone help me please? This version of cake is deprecated for this plugin?

**Comment by webtechnick** [comment]
1.3 still has support, it's in its own branch now: https://github.com/webtechnick/CakePHP-Facebook-Plugin/tree/cakephp1.3
