### ISSUE TITLE
Infinite reload

### ISSUE THREAD

**Issue by edap** [webtechnick/CakePHP-Facebook-Plugin#8]
Hey Nick, thanks for your plugin.
In the lasts months, something goes wrong, I have this problem:
If I am logged in facebook and I go on the website that I'm working on,  there is an reload every second.

I've seen that you have the same problem in the application example.
http://facebook.webtechnick.com/
I'm triyng to figure out whats happen, It's seems that at the connect.php line 61 the getSession() method fail.

Have you some suggestion about?

**Comment by webtechnick** [comment]
Make sure you're using the latest plugin.  Line 61 is a comment in the latest version of the Facebook Plugin.  Assuming you meant line 60, how exactly does it fail?  I don't seem to be seeing the same reload issue you're having even on the example application.  

What are the steps required to reproduce this issue?

Better yet, do you have a test case I can use?

Thanks,
Nick

**Comment by webtechnick** [comment]
You need to point localhost.local to 127.0.0.1 to avoid this redirect loop on localhost.
http://ardentdev.com/no-facebook-connect-cookies-for-localhost-development/

"While doing some Facebook Connect development, I found that the expected cookies were not being set when developing on localhost.  To fix the problem, I added localhost.local to my hosts file (pointing at 127.0.0.1) and changed the settings for my Facebook application to use localhost.local as the base domain."

**Comment by edap** [comment]
thanks, it works ;)
