### ISSUE TITLE
Connect, debugger error

### ISSUE THREAD

**Issue by heshanh** [webtechnick/CakePHP-Facebook-Plugin#86]
When i attach Facebook.Connect to the component array it throws this error

Fatal error: Class 'Debugger' not found in ..\plugins\Facebook\Controller\Component\ConnectComponent.php on line 250

250 is the closing bracket of the class

**Comment by webtechnick** [comment]
You're trying to use a 2.0 plugin in a 1.3 application.  Use the 1.3 branch of this plugin for your 1.3 application.

**Comment by heshanh** [comment]
I'm using 2.1.3

**Comment by webtechnick** [comment]
Then why do you have it in "plugins"?  It should be in "Plugin"

**Comment by heshan-wva** [comment]
Its in the plugins folder next to app, lib, on the root. I'll move it to the app/Plugin when I go home. Although the plugin actually loads and I can use ->comment() an ->share().
share() actually renders a link instead of the nice blue button. 

Thanks for the heads up. wouldnt have picked it up :)

**Comment by heshanh** [comment]
Hey Nick,
I moved it to /app/Plugin its still the same

Cake v 2.1.3
Plugin v 3.1.1

Fatal error: Class 'Debugger' not found in ..\app\Plugin\Facebook\Controller\Component\ConnectComponent.php on line 250

# appController

```
public $helpers = array( "Facebook.Facebook");
public $components = array('Session',
'Auth' => array(
    'authenticate' => array(
        'Form' => array(
            'fields' => array('username' => 'username')
        )
    ),
    'authorize' => 'Controller'
),
'Facebook.Connect' => array('model' => 'User')
```

);

**Comment by webtechnick** [comment]
Sounds like you don't have a full checkout of CakePHP.  Debugger is a library in CakePHP.  Line 250 is the end of the file.  Make sure you have Debugger.php file in your cake library.

**Comment by heshanh** [comment]
its there, in lib\cake\utility

and \Test\case\utility 

i also have DebugKit running from the root plugins folder

**Comment by webtechnick** [comment]
Not sure, this is an odd issue I haven't heard of.  Try adding:

App::uses('Debugger', 'Utility');

To your AppController or something.
