### ISSUE TITLE
Function css on non-object

### ISSUE THREAD

**Issue by bluestella** [webtechnick/CakePHP-Facebook-Plugin#91]
I have encountered an error with my development. Trying to do Facebook Authentication basics and was having to do the debug activity and stumbledupon this error, which i cannot fix for now. Maybe there's some solution to this? or possibly an issue that was not yet addressed?

Error: Call to a member function css() on a non-object  
File: C:\wamp\www\facebook_example\app\View\Layouts\facebook.ctp  
Line: 3

**Comment by timworld** [comment]
I encountered the same issue more or less. Did you get a solution for this problem?

Regards,
Tim
